# Generated by Django 6.0 on 2025-12-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aup_number', models.CharField(max_length=50, verbose_name='Номер АУП')),
                ('education_type', models.CharField(max_length=100, verbose_name='Вид образования')),
                ('education_level', models.CharField(max_length=100, verbose_name='Уровень образования')),
                ('direction', models.CharField(max_length=255, verbose_name='Направление (специальность)')),
                ('direction_code', models.CharField(max_length=50, verbose_name='Код специальности')),
                ('qualification', models.CharField(max_length=100, verbose_name='Квалификация')),
                ('profile', models.CharField(max_length=255, verbose_name='Профиль (специализация)')),
                ('standard_type', models.CharField(max_length=100, verbose_name='Тип стандарта')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год набора')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(blank=True, max_length=100, null=True, verbose_name='Блок')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Шифр')),
                ('part', models.CharField(blank=True, max_length=100, null=True, verbose_name='Часть')),
                ('module', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модуль')),
                ('record_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип записи')),
                ('name', models.CharField(max_length=255, verbose_name='Дисциплина')),
                ('period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Период контроля')),
                ('load_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Нагрузка')),
                ('amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество')),
                ('measurement_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ед. изм.')),
                ('zet', models.CharField(blank=True, max_length=50, null=True, verbose_name='ЗЕТ')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='programs.educationalprogram')),
            ],
        ),
    ]
