# Generated by Django 6.0 on 2026-02-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Блок')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Модуль')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Часть')),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Уровень образования')),
            ],
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид образования')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Факультет')),
            ],
        ),
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид нагрузки')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Квалификация')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Семестр/Период')),
            ],
        ),
        migrations.CreateModel(
            name='StandardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип стандарта')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код направления')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'unique_together': {('code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Шифр')),
                ('name', models.CharField(max_length=255, verbose_name='Дисциплина')),
                ('amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество')),
                ('measurement_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ед. изм.')),
                ('zet', models.CharField(blank=True, max_length=50, null=True, verbose_name='ЗЕТ')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.disciplineblock', verbose_name='Блок')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.disciplinemodule', verbose_name='Модуль')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.disciplinepart', verbose_name='Часть')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineMarking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markings', to='programs.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255, verbose_name='Профиль (специализация)')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год набора')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.direction', verbose_name='Направление')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.educationlevel', verbose_name='Уровень образования')),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.educationtype', verbose_name='Вид образования')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.faculty', verbose_name='Факультет')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.qualification', verbose_name='Квалификация')),
                ('standard_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.standardtype', verbose_name='Тип стандарта')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='programs.educationalprogram'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='load_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.loadtype', verbose_name='Вид нагрузки'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='programs.semester', verbose_name='Семестр'),
        ),
        migrations.CreateModel(
            name='SemesterControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(max_length=100, verbose_name='Вид контроля')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='programs.discipline')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.semester', verbose_name='Семестр')),
            ],
        ),
    ]
