# Generated by Django 6.0 on 2026-02-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='profile',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Профиль (специализация)'),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Год набора'),
        ),
    ]
