# Generated by Django 6.0 on 2026-02-13 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_discipline_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='block',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='code',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='load_type',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='module',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='part',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='program',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='zet',
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название дисциплины'),
        ),
        migrations.CreateModel(
            name='ProgramDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Шифр')),
                ('amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество')),
                ('measurement_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ед. изм.')),
                ('zet', models.CharField(blank=True, max_length=50, null=True, verbose_name='ЗЕТ')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.disciplineblock', verbose_name='Блок')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_disciplines', to='programs.discipline', verbose_name='Дисциплина')),
                ('load_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.loadtype', verbose_name='Вид нагрузки')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.disciplinemodule', verbose_name='Модуль')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.disciplinepart', verbose_name='Часть')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='programs.educationalprogram')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='programs.semester', verbose_name='Семестр')),
            ],
        ),
        migrations.AlterField(
            model_name='disciplinemarking',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markings', to='programs.programdiscipline'),
        ),
        migrations.AlterField(
            model_name='semestercontrol',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='programs.programdiscipline'),
        ),
    ]
